name = "PID"
uuid = "fa9cea79-542e-4576-82bf-5014c01fb628"
authors = ["jekyllstein <jekyllstein@gmail.com>"]
version = "0.1.0"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[targets]
test = ["Plots"]
